### ISSUE TITLE
Last 15 lines from /Users/Tim/Library/Logs/Homebrew/osvr-core/01.cmake:

### ISSUE THREAD

**Issue by unixneo** [OSVR/Homebrew-OSVR#8] opened 2016-11-07 05:52 UTC
Reporting error installing osvr-core on osx :

```
> ==> Installing osvr/osvr/osvr-core
> ==> Cloning https://github.com/OSVR/OSVR-Core.git
> Cloning into '/Users/Tim/Library/Caches/Homebrew/osvr-core--git'...
> remote: Counting objects: 3265, done.
> remote: Compressing objects: 100% (2640/2640), done.
> remote: Total 3265 (delta 812), reused 2257 (delta 551), pack-reused 0
> Receiving objects: 100% (3265/3265), 6.89 MiB | 1.20 MiB/s, done.
> Resolving deltas: 100% (812/812), done.
> Checking connectivity... done.
> ==> Checking out branch master
> ==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cella
> Last 15 lines from /Users/Tim/Library/Logs/Homebrew/osvr-core/01.cmake:
> -- Looking for intrin.h - not found
> -- Looking for byteswap.h
> -- Looking for byteswap.h - not found
> -- Performing Test OSVR_HAVE_WORKING_MS_BYTESWAPS
> -- Performing Test OSVR_HAVE_WORKING_MS_BYTESWAPS - Failed
> -- Performing Test OSVR_HAVE_WORKING_BSWAP
> -- Performing Test OSVR_HAVE_WORKING_BSWAP - Failed
> -- Performing Test OSVR_HAVE_WORKING_BSWAP_UNDERSCORE
> -- Performing Test OSVR_HAVE_WORKING_BSWAP_UNDERSCORE - Failed
> -- Performing Test OSVR_HAVE_WORKING_UNDERSCORES_BSWAP
> -- Performing Test OSVR_HAVE_WORKING_UNDERSCORES_BSWAP - Failed
> -- Could NOT find Markdown (missing:  MARKDOWN_EXECUTABLE) 
> -- Configuring incomplete, errors occurred!
> See also "/tmp/osvr-core-20161107-22390-e8ctam/build/CMakeFiles/CMakeOutput.log".
> See also "/tmp/osvr-core-20161107-22390-e8ctam/build/CMakeFiles/CMakeError.log".
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> https://github.com/osvr/homebrew-osvr/issues
> 
```

**Comment by unixneo** [comment] 2016-11-07 05:56
Tried again, no joy:

```
Tims-MacBook-Air-2:tmp Tim$ vi /Users/Tim/Library/Logs/Homebrew/osvr-core/01.cmake
Tims-MacBook-Air-2:tmp Tim$ mv /Users/Tim/Library/Logs/Homebrew/osvr-core/01.cmake /Users/Tim/Library/Logs/Homebrew/osvr-core/01.cmake.orig
Tims-MacBook-Air-2:tmp Tim$ brew install osvr-core --HEAD

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
pcap_dnsproxy

==> Installing osvr-core from osvr/osvr
==> Cloning https://github.com/OSVR/OSVR-Core.git
Updating /Users/Tim/Library/Caches/Homebrew/osvr-core--git
==> Checking out branch master
Synchronizing submodule url for 'submodules/hidapi'
Synchronizing submodule url for 'submodules/jsoncpp'
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cella
Last 15 lines from /Users/Tim/Library/Logs/Homebrew/osvr-core/01.cmake:
-- Looking for intrin.h - not found
-- Looking for byteswap.h
-- Looking for byteswap.h - not found
-- Performing Test OSVR_HAVE_WORKING_MS_BYTESWAPS
-- Performing Test OSVR_HAVE_WORKING_MS_BYTESWAPS - Failed
-- Performing Test OSVR_HAVE_WORKING_BSWAP
-- Performing Test OSVR_HAVE_WORKING_BSWAP - Failed
-- Performing Test OSVR_HAVE_WORKING_BSWAP_UNDERSCORE
-- Performing Test OSVR_HAVE_WORKING_BSWAP_UNDERSCORE - Failed
-- Performing Test OSVR_HAVE_WORKING_UNDERSCORES_BSWAP
-- Performing Test OSVR_HAVE_WORKING_UNDERSCORES_BSWAP - Failed
-- Could NOT find Markdown (missing:  MARKDOWN_EXECUTABLE) 
-- Configuring incomplete, errors occurred!
See also "/tmp/osvr-core-20161107-25254-10lqbmw/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/osvr-core-20161107-25254-10lqbmw/build/CMakeFiles/CMakeError.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/osvr/homebrew-osvr/issues

These open issues may also help:
Last 15 lines from /Users/Tim/Library/Logs/Homebrew/osvr-core/01.cmake: https://github.com/OSVR/Homebrew-OSVR/issues/8
```

**Comment by godbyk** [comment] 2016-11-07 05:57
Can you post the full contents of `/Users/Tim/Library/Logs/Homebrew/osvr-core/01.cmake`?

Thanks!

**Comment by unixneo** [comment] 2016-11-07 09:03
Thanks!  Here it is!

```
Tims-MacBook-Air-2:~ Tim$ cat /Users/Tim/Library/Logs/Homebrew/osvr-core/01.cmake
2016-11-07 12:55:20 +0700

cmake
..
-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/osvr-core/HEAD-cb295fe
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-Wno-dev

-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could not get revision information from Git! Calling this just version 0.6!
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework  
-- Could NOT find SDL2 (missing:  SDL2_LIBRARY SDL2_INCLUDE_DIR SDL2_SDLMAIN_LIBRARY) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found JsonCpp: /usr/local/lib/cmake/jsoncpp  
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Performing Test OSVR_HAVE_STD_SHARED_PTR
-- Performing Test OSVR_HAVE_STD_SHARED_PTR - Success
-- Performing Test OSVR_HAVE_STD_UNIQUE_PTR
-- Performing Test OSVR_HAVE_STD_UNIQUE_PTR - Success
CMake Warning at /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake-local/BoostTargets.cmake:25 (find_package)
  CMakeLists.txt:295 (include)


CMake Warning at /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake-local/BoostTargets.cmake:25 (find_package)
  CMakeLists.txt:295 (include)


CMake Warning at /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake-local/BoostTargets.cmake:25 (find_package)
  CMakeLists.txt:295 (include)


CMake Warning at /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake-local/BoostTargets.cmake:25 (find_package)
  CMakeLists.txt:295 (include)


CMake Warning at /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake-local/BoostTargets.cmake:25 (find_package)
  CMakeLists.txt:295 (include)


CMake Warning at /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake-local/BoostTargets.cmake:25 (find_package)
  CMakeLists.txt:295 (include)


-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   thread
--   system
--   date_time
--   chrono
--   program_options
--   filesystem
CMake Error at cmake-local/BoostTargets.cmake:29 (message):
  Using an unreviewed Boost version - inspect the Boost Interprocess release
  notes/changelog/diffs to see if any ABI breaks took place as they may
  affect client/server interoperability.
Call Stack (most recent call first):
  CMakeLists.txt:295 (include)


CMake Error at cmake-local/BoostTargets.cmake:30 (message):
  The corresponding source file to update is
  src/osvr/Common/IPCRingBuffer.cpp
Call Stack (most recent call first):
  CMakeLists.txt:295 (include)


-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Git's description of the current revision indicates this is a prerelease of 07.34: version_07.33-310-ge75e92c

-- Configuring the VRPN suite version 07.34.0~prerelease-git-07.33-310-ge75e92c using the CMake-based build system

-- Checking uint32_t in HID callback signature... TRUE
-- Checking UInt32 in HID callback signature... TRUE
-- Found MacHID: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreFoundation.framework  
-- Found quatlib: quat  
-- Performing Test OSVR_HAVE_STRUCT_TIMEVAL_IN_SYS_TIME_H
-- Performing Test OSVR_HAVE_STRUCT_TIMEVAL_IN_SYS_TIME_H - Success
-- Performing Test OSVR_HAVE_STRUCT_TIMEVAL_IN_WINSOCK2_H
-- Performing Test OSVR_HAVE_STRUCT_TIMEVAL_IN_WINSOCK2_H - Failed
-- Looking for std::align
-- Looking for std::align - found
-- Generating /tmp/osvr-core-20161107-25254-10lqbmw/build/src/osvr/Util/ReportTypesX.h
-- Performing Test SUPPORTS_W_FLAG
-- Performing Test SUPPORTS_W_FLAG - Success
-- Performing Test SUPPORTS_WALL_FLAG
-- Performing Test SUPPORTS_WALL_FLAG - Success
-- Performing Test SUPPORTS_WEXTRA_FLAG
-- Performing Test SUPPORTS_WEXTRA_FLAG - Success
-- Performing Test SUPPORTS_WNO_MAYBE_UNINITIALIZED_FLAG
-- Performing Test SUPPORTS_WNO_MAYBE_UNINITIALIZED_FLAG - Success
-- Generating /tmp/osvr-core-20161107-25254-10lqbmw/build/src/osvr/Util/ClientCallbackTypesC.h
-- Looking for intrin.h
-- Looking for intrin.h - not found
-- Looking for byteswap.h
-- Looking for byteswap.h - not found
-- Performing Test OSVR_HAVE_WORKING_MS_BYTESWAPS
-- Performing Test OSVR_HAVE_WORKING_MS_BYTESWAPS - Failed
-- Performing Test OSVR_HAVE_WORKING_BSWAP
-- Performing Test OSVR_HAVE_WORKING_BSWAP - Failed
-- Performing Test OSVR_HAVE_WORKING_BSWAP_UNDERSCORE
-- Performing Test OSVR_HAVE_WORKING_BSWAP_UNDERSCORE - Failed
-- Performing Test OSVR_HAVE_WORKING_UNDERSCORES_BSWAP
-- Performing Test OSVR_HAVE_WORKING_UNDERSCORES_BSWAP - Failed
-- Could NOT find Markdown (missing:  MARKDOWN_EXECUTABLE) 
-- Configuring incomplete, errors occurred!
See also "/tmp/osvr-core-20161107-25254-10lqbmw/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/osvr-core-20161107-25254-10lqbmw/build/CMakeFiles/CMakeError.log".

HOMEBREW_VERSION: 1.0.9-74-g586b35f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 586b35fe29a2bcf3edc6869345e425df6df4a78c
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 304d5c94588aa1898d9128d984d0fa0825ad721f
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 0
Clang: 8.0 build 800
Git: 2.9.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102
macOS: 10.12.1-x86_64
Xcode: 8.1
CLT: N/A
X11: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_PATH: /usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/ilmbase/lib/pkgconfig:/usr/local/opt/openexr/lib/pkgconfig:/usr/local/opt/opencv/lib/pkgconfig:/usr/local/opt/jsoncpp/lib/pkgconfig:/usr/local/opt/libusb/lib/pkgconfig:/usr/local/opt/eigen/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/cmake/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/libpng/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/openexr/bin:/usr/local/opt/numpy/bin:/usr/local/opt/opencv/bin:/usr/bin:/bin:/usr/sbin:/sbin
Tims-MacBook-Air-2:~ Tim$ 

```

**Comment by godbyk** [comment] 2016-11-07 18:05
The root of the problem is that the version of Boost installed by Homebrew (version 1.62.0) is newer than that supported by OSVR-Core. I've written a patch to fix this. See https://github.com/OSVR/OSVR-Core/pull/495. Once that patch is merged to the master branch, the Homebrew recipe should work again.

(CMake needs to be updated to recognize the newer Boost version, too, but that isn't causing any actual problems.)

**Comment by rpavlik** [comment] 2016-11-08 17:12
I've since merged the Boost 1.62 support patch

**Comment by unixneo** [comment] 2016-11-10 05:22
Thank you!  Works now!

**Closed as completed** 2016-11-10 05:22 UTC

**Comment by ShaneHudson** [comment] 2017-06-05 16:53
I have this exact issue with boost 1.64.0_1

**Comment by chargedneuron** [comment] 2017-06-13 00:25
> I have this exact issue with boost 1.64.0_1

Same issue...

**Comment by ShaneHudson** [comment] 2017-06-13 09:04
This worked for me:

```
brew unlink boost
brew install boost@1.60
brew link boost@1.60 --force
brew install osvr-core --HEAD
```

But I didn't manage to figure out how to use osvr with dk2 for webvr, which I was under the impression would work.

**Comment by chargedneuron** [comment] 2017-06-14 02:35
That seemed to fix my issue. Finished compiling but haven't tested against the hardware. Thanks for the heads up!
